baseURL = "https://devnotes.rickdgray.com"

languageCode = "en-us"
DefaultContentLanguage = "en"
title = "Rick's Dev Notes"

hasCJKLanguage = false
metaDataFormat = "yaml"

defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false
enableMissingTranslationPlaceholders = false

[params]
  description = "Dev notes you can use"
  github_repository = "https://github.com/rickdgray/notes"
  version = "0.3.1"

  # Analytic section
  google_analytics_id = "" # Your Google Analytics tracking id
  google_site_verification = "" # Your Google Site Verification for Search Console

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark.renderer]
      unsafe = true
  [markup.tableOfContents]
      startLevel = 2
      endLevel = 6
      ordered = false

[outputs]
  home = ["HTML"]
